# Generated by Django 3.0.5 on 2020-05-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='service',
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='viewing date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Movie')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='services',
            field=models.ManyToManyField(to='main_app.Service'),
        ),
    ]
